package net.andreu.confusio;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;

import org.xml.sax.SAXException;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.stage.FileChooser;
import javafx.stage.FileChooser.ExtensionFilter;

public class SampleController {
	@FXML
	private Button fitxer;
	@FXML
	private Button desa;
	@FXML
	private Label direc;
	@FXML
	private Label sec;
	@FXML
	private Label capEstudi;
	@FXML
	private Label coord;
	@FXML
	private Button calcula;
	@FXML
	private Label nomDirec;
	@FXML
	private Label nomSec;
	@FXML
	private Label nomCapEstudi;
	@FXML
	private Label nomCoord;

	// Event Listener on Button[#fitxer].onMouseClicked
	@FXML
	public void cargaFitxer(MouseEvent event) throws ParserConfigurationException, SAXException, IOException {
		FileChooser buscador = new FileChooser();
		buscador.getExtensionFilters().addAll(new ExtensionFilter("XML Files", "*.xml"));
		File selectedFile = buscador.showOpenDialog(null);
		
		if(selectedFile != null){
			SAXParserFactory fabrica=SAXParserFactory.newInstance();
	        fabrica.setNamespaceAware(true);
	        SAXParser parser=fabrica.newSAXParser();
	        for(int i=0; i<selectedFile.length(); i++){
	        	InputStream fitxer = new FileInputStream(selectedFile);
	        	parser.parse(fitxer,new Processar());
	        }
		}
	}
	
	// Event Listener on Button[#desa].onMouseClicked
	@FXML
	public void generarFitxer(MouseEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#calcula].onMouseClicked
	@FXML
	public void canviaNoms(MouseEvent event) {
		// TODO Autogenerated
	}
}
